[package]
name = "messaging"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
rocket = { version = "0.5.1", features = ["json", "serde_json"] }
serde = "1.0.219"
tokio = "1.46.1"
tokio-tungstenite = "0.27.0"
